version: 2 
jobs: 
  build: 
    working_directory: ~/test-fn-api 
    docker: 
      - image: circleci/openjdk:8u131-jdk 
    steps: 
      - checkout 
      - restore_cache: 
          key: test-fn-api-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline 
      - save_cache: 
          paths:
            - ~/.m2
          key: test-fn-api-{{ checksum "pom.xml" }}
      - run: mvn package 
      - store_test_results: 
          path: target/surefire-reports
      - store_artifacts: 
          path: target/TEST-FN-API-0.0.1-SNAPSHOT.jar